<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>NEXGov.Mediator Contributors</Authors>
    <Company>NEXGov</Company>
    <Product>NEXGov.Mediator</Product>
    <Copyright>Copyright (c) NEXGov.Mediator Contributors</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

</Project>
