using NEXGov.Mediator.Pipeline;

namespace NEXGov.Mediator.IntegrationTests;

// MED-024 integration fixtures: nested-generic-response closing for AddOpenBehavior, through a
// real DI container. ComplexBehaviorResponse<T> is a wrapper type unique to this file, so
// ClosedBehaviorRegistrar's structural matching (against each behavior's own declared response
// pattern) naturally isolates these fixtures from every other IPipelineBehavior<,> in this
// shared assembly without needing a TypeEvaluator exclusion list — see the UnitTests
// counterpart file for the same design rationale.

public sealed class ClosedBehaviorDiMarker;

public sealed record ComplexBehaviorResponse<T>(T Value);

public sealed record ComplexPing(int Id) : IRequest<ComplexBehaviorResponse<string>>;

public sealed class ComplexPingHandler : IRequestHandler<ComplexPing, ComplexBehaviorResponse<string>>
{
    private readonly List<string> _log;

    public ComplexPingHandler(List<string> log) => _log = log;

    public Task<ComplexBehaviorResponse<string>> Handle(ComplexPing request, CancellationToken cancellationToken)
    {
        _log.Add("Handler");
        return Task.FromResult(new ComplexBehaviorResponse<string>("handled"));
    }
}

// Every closed IPipelineBehavior<,> generated by ClosedBehaviorRegistrar for this file resolves
// through this single open implementation. Depends on a scoped dependency (proving the
// generated closed registration participates in ordinary DI scoping like any other behavior,
// not something special-cased) and forwards the CancellationToken it was handed straight into
// next() (proving nothing in the closing/generation path wraps or replaces it).
public sealed class ComplexNestedBehavior<TRequest, TValue> : IPipelineBehavior<TRequest, ComplexBehaviorResponse<TValue>>
    where TRequest : notnull
{
    private readonly IDiScopedDependency _dependency;
    private readonly List<string> _log;

    public ComplexNestedBehavior(IDiScopedDependency dependency, List<string> log)
    {
        _dependency = dependency;
        _log = log;
    }

    public async Task<ComplexBehaviorResponse<TValue>> Handle(
        TRequest request, RequestHandlerDelegate<ComplexBehaviorResponse<TValue>> next, CancellationToken cancellationToken)
    {
        _log.Add($"Nested.Before:{_dependency.InstanceId}");
        var response = await next(cancellationToken).ConfigureAwait(false);
        _log.Add($"Nested.After:{_dependency.InstanceId}");
        return response;
    }
}

// --- Cancellation forwarding proof ---

public sealed record CancellationAwarePing(int Id) : IRequest<ComplexBehaviorResponse<string>>;

public sealed class CancellationAwarePingHandler : IRequestHandler<CancellationAwarePing, ComplexBehaviorResponse<string>>
{
    public Task<ComplexBehaviorResponse<string>> Handle(CancellationAwarePing request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return Task.FromResult(new ComplexBehaviorResponse<string>("handled"));
    }
}

// --- Exception pipeline composition ---

public sealed record NestedResponseExceptionPing(int Id) : IRequest<ComplexBehaviorResponse<string>>;

public sealed class NestedResponseExceptionPingHandler : IRequestHandler<NestedResponseExceptionPing, ComplexBehaviorResponse<string>>
{
    public Task<ComplexBehaviorResponse<string>> Handle(NestedResponseExceptionPing request, CancellationToken cancellationToken)
        => throw new InvalidOperationException("boom");
}

public sealed class NestedResponseExceptionHandler
    : IRequestExceptionHandler<NestedResponseExceptionPing, ComplexBehaviorResponse<string>, InvalidOperationException>
{
    public Task Handle(
        NestedResponseExceptionPing request,
        InvalidOperationException exception,
        RequestExceptionHandlerState<ComplexBehaviorResponse<string>> state,
        CancellationToken cancellationToken)
    {
        state.SetHandled(new ComplexBehaviorResponse<string>("recovered"));
        return Task.CompletedTask;
    }
}

// --- Processor pipeline composition ---
// Closed (non-generic) pre/post processors targeting ComplexPing directly, so enabling
// AutoRegisterRequestProcessors here does not also need to reason about unrelated open generic
// processors elsewhere in this shared assembly.

public sealed class ComplexPreProcessor : IRequestPreProcessor<ComplexPing>
{
    private readonly List<string> _log;

    public ComplexPreProcessor(List<string> log) => _log = log;

    public Task Process(ComplexPing request, CancellationToken cancellationToken)
    {
        _log.Add("Pre");
        return Task.CompletedTask;
    }
}

public sealed class ComplexPostProcessor : IRequestPostProcessor<ComplexPing, ComplexBehaviorResponse<string>>
{
    private readonly List<string> _log;

    public ComplexPostProcessor(List<string> log) => _log = log;

    public Task Process(ComplexPing request, ComplexBehaviorResponse<string> response, CancellationToken cancellationToken)
    {
        _log.Add("Post");
        return Task.CompletedTask;
    }
}
